### ISSUE TITLE
Issue still says authored by "PX Blue"

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-database#7]
## Describe the bug

Milestones ≤ Q3 2021 (R21) have their `author` fields still saying `PX Blue`

## What is the expected behavior?

That field should say `Brightlayer UI` instead

## What are the steps to reproduce?
1. Go to https://brightlayer-ui-dev.github.io/roadmap
2. Show Q3 2021 roadmap

## Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/149720486-4a378a32-835d-49cb-9beb-4e1e543a2287.png)

Docit is tagging all "PX Blue" ones "PX Blue" (the "PX Blue" tag should be hidden)

**Comment by emclaug2** [comment]
@joebochill @huayunh This might belong on the doc-it repo instead; do you think we should rewrite historic entries, or should be updated doc-it to hide the "BLUI" and "PX Blue" authors?

**Comment by huayunh** [comment]
It works for me either way; the database is used internally only so it is not as strict as our changelog / release notes.

**Comment by bkarambe** [comment]
Issue still exists.
